# services:
#   cliente-prueba:
#     image: alpine
#     command: tail -f /dev/null
#     networks:
#       - mi_red_privada

#   servidor-prueba:
#     image: alpine
#     command: tail -f /dev/null
#     networks:
#       - mi_red_privada

# networks:
#   mi_red_privada:
#     driver: bridge


services:

  mi-api:
    image: kennethreitz/httpbin
    networks:
      - red_interna

  # El recepcionista 
  apache-proxy:
    image: bitnamilegacy/apache:2.4
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./apache/proxy.conf:/opt/bitnami/apache/conf/vhosts/proxy.conf
      - ./certs:/opt/bitnami/apache/conf/certs
    networks:
      - red_interna
      - red_publica
  
  kong:
    image: kong:3.4.0-ubuntu
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001 
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
    ports:
      - "8000:8000"
    networks:
      - red_interna
      - red_publica

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - red_interna
    
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${DECK_SECRETO_GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${DECK_SECRETO_GRAFANA_PASSWORD}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana 
    networks:
      - red_interna
      - red_publica

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${DECK_SECRETO_KEYCLOACK_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${DECK_SECRETO_KEYCLOACK_PASSWORD}
    ports:
      - "8082:8080" 
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./api-realm-export.json:/opt/keycloak/data/import/api-realm-export.json
    networks:
      - red_interna
      - red_publica
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    
    restart: on-failure
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    
    expose: #solo abre el puerto para contenedores dentro de la misma red
      - "16686"
      - "4318"
    
   

    networks:
      - red_interna

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - "9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - red_interna
    
    




networks:
  red_interna:
    internal: true
    driver: bridge
  red_publica:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  keycloak_data:
  elastic_data: