# <VirtualHost *:8080>
#     ServerName localhost

#     # Esto redirecciona el trafico que llegue a la raiz hacia mi-api
#     ProxyPreserveHost On
#     ProxyPass / http://kong:8000/
#     ProxyPassReverse / http://kong:8000/
# </VirtualHost>

# --- KONG ---
<VirtualHost *:8080>
    ServerName ${DECK_DOMAIN_KONG}
    Redirect permanent / https://${DECK_DOMAIN_KONG}:8443/
</VirtualHost>

<VirtualHost *:8443>
    ServerName ${DECK_DOMAIN_KONG}

    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache/conf/certs/apache.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/certs/apache.key"

    ProxyPreserveHost On
    ProxyPass / http://kong:8000/
    ProxyPassReverse / http://kong:8000/
</VirtualHost>

# --- GRAFANA ---
<VirtualHost *:8080>
    ServerName ${DECK_DOMAIN_GRAFANA}
    Redirect permanent / https://${ DECK_DOMAIN_GRAFANA}:8443/
</VirtualHost>

<VirtualHost *:8443>
    ServerName ${DECK_DOMAIN_GRAFANA}

    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache/conf/certs/apache.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/certs/apache.key"

    ProxyPreserveHost On
    ProxyPass / http://grafana:3000/
    ProxyPassReverse / http://grafana:3000/
</VirtualHost>

# --- KEYCLOAK ---
<VirtualHost *:8080>
    ServerName ${env DECK_DOMAIN_KEYCLOAK}
    Redirect permanent / https://${env DECK_DOMAIN_KEYCLOAK}:8443/
</VirtualHost>

<VirtualHost *:8443>
    ServerName ${DECK_DOMAIN_KEYCLOAK}

    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache/conf/certs/apache.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/certs/apache.key"

    ProxyPreserveHost On
    ProxyPass / http://keycloak:8080/
    ProxyPassReverse / http://keycloak:8080/
</VirtualHost>

# --- PROMETHEUS ---
<VirtualHost *:8080>
    ServerName ${DECK_DOMAIN_PROMETHEUS}
    Redirect permanent / https://${ DECK_DOMAIN_PROMETHEUS}:8443/
</VirtualHost>

<VirtualHost *:8443>
    ServerName ${DECK_DOMAIN_PROMETHEUS}

    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache/conf/certs/apache.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/certs/apache.key"

    ProxyPreserveHost On
    ProxyPass / http://prometheus:9090/
    ProxyPassReverse / http://prometheus:9090/
</VirtualHost>

#--- JAEGER ---
<VirtualHost *:8080>
    ServerName ${DECK_DOMAIN_JAEGER}
    Redirect permanent / https://${DECK_DOMAIN_JAEGER}:8443/
</VirtualHost>

<VirtualHost *:8443>
    ServerName ${DECK_DOMAIN_JAEGER}

    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache/conf/certs/apache.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/certs/apache.key"

    ProxyPreserveHost On
    ProxyPass / http://jaeger:16686/
    ProxyPassReverse / http://jaeger:16686/
</VirtualHost>


