# <VirtualHost *:8080>
#     ServerName localhost

#     # Esto redirecciona el trafico que llegue a la raiz hacia mi-api
#     ProxyPreserveHost On
#     ProxyPass / http://kong:8000/
#     ProxyPassReverse / http://kong:8000/
# </VirtualHost>

<VirtualHost *: 8080>
    serverName localhost
    Redirect permanent / https://localhost:8443/
</VirtualHost>

<VirtualHost *:8443>
    ServerName localhost

    SSLEngine on
    SSLCertificateFIle "/opt/bitnami/apache/conf/certs/apache.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache/conf/certs/apache.key"

    ProxyPreserveHost On
    ProxyPass / http://kong:8000/
    ProxyPassReverse / http://kong:8000/
</VirtualHost>