name: Validacion de Infraestructura (decK)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auditoria-kong:
    runs-on: ubuntu-latest 

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Validar sintaxis y lógica de kong.yaml
        run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace kong/deck:latest file validate kong.yaml